services:
  redis_cache:
    image: redis:alpine
    container_name: saas_redis_container
    restart: always
    ports:
      - "${REDIS_PORT_EXTERNAL}:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_saas_data:/data
    networks:
      - saas_net # <--- Referencia interna

volumes:
  redis_saas_data:

networks:
  saas_net: # <--- Nombre interno fijo
    name: ${NETWORK_NAME} # <--- Nombre real externo
    external: true